#!/usr/bin/env python3
# Written by Joseph P.Vera
# 2024-11

"""
Usage:
    python3 point_groups.py [--qe] [--target]

Examples VASP:
    python3 point_groups.py wfc_s2_k1_b430_r.vasp                              
    python3 point_groups.py wfc_s2_k1_b430_r.vasp wfc_s2_k1_b430_i.vasp       
    python3 point_groups.py wfc_s2_k1_b430_r.vasp --target D_2d
    python3 point_groups.py wfc_s2_k1_b431_r.vasp wfc_s2_k1_b432_r.vasp

Examples QE:    
    python3 point_groups.py --qe wfc_band430_dw.xsf 
    python3 point_groups.py --qe wfc_band430_dw.xsf --target D_2d
    python3 point_groups.py --qe wfc_band431_dw.xsf wfc_band432_dw.xsf    

Point group for use is read from correction.json

Identifies the irreducible representation to which a Kohn-Sham orbital
belongs, from either:
  - VASP in VESTA format (.vasp), such as produced by ks-orbital.py /
    wav.save2vesta() -- this is the DEFAULT, or
  - Quantum ESPRESSO in XCrySDen structure format (.xsf), i.e. a file
    that embeds a 'BEGIN_BLOCK_DATAGRID_3D' volumetric section for a
    single band (e.g. as produced by pp.x), pass --qe to select this.

Method:
  1. The real-space FFT grid (nx,ny,nz) is parsed from the input file
     (.vasp by default, or .xsf with --qe; see read_vesta_grid /
     read_xsf_grid). For .xsf, XCrySDen's convention for periodic data
     repeats the first grid point as an extra last point along each
     axis (so a genuine nx x ny x nz FFT grid is stored as (nx+1) x
     (ny+1) x (nz+1) values); that redundant last point is dropped on
     read to recover the intrinsic FFT grid, exactly as QE itself uses
     it.
  2. The 48 operations of O_h (the full cubic holohedry: all signed
     permutations of x,y,z) are generated as the universal PARENT group,
     valid whenever the cell axes coincide with the cubic cell axes,
     as for a defect in a zincblende/rocksalt/diamond-type lattice with
     the cell aligned to x,y,z as in the POSCAR. Every point group that
     can occur as the local symmetry of such a defect (T_d, T, O, O_h,
     D_2d, D_4h, C_3v, D_3d, C_2v, S_4, C_4v, ..., any of the 32
     crystallographic point groups compatible with a cubic cell) is a
     subgroup of O_h, so this single parent group replaces the old
     T_d-only (24-operation) parent.
  3. GIVEN ANY point-group name recognized by point_groups_lib.py (read from
     correction.json, or given explicitly with --target), the script
     searches for that group as a concrete subgroup of the 48 O_h
     operations: it enumerates subgroups generated by pairs of O_h
     operations, keeps the ones whose order matches, computes their
     TRUE conjugacy classes by matrix multiplication (no per-group
     hand-written logic), and matches those classes against the class
     list declared for that group in point_groups_lib.py. Each valid match
     is one physical "orientation" (e.g. one of the four <111> axes for
     C_3v), exactly what the old axis-search functions did by hand
     for T_d/D_2d/C_3v specifically, done here once, generically, for
     any group in the catalog.
  4. For each orientation found, phi(R^-1 (r-c)+c) is interpolated on
     the grid (periodic boundary conditions, cubic spline). For n input
     .vasp files the trace of the n x n normalized overlap matrix
     Tr[S(R)], S_ij(R) = <phi_i|R phi_j> / sqrt(<phi_i|phi_i><phi_j|phi_j>),
     is used as the character chi(R) -- this is the correct
     generalization for ANY degeneracy order n: giving 1 file analyzes
     the non-degenerate case, 2 files the doubly-degenerate case, 3
     files the triply-degenerate case, and so on for as many bands as
     are given (for n=1 the formula reduces exactly to the familiar
     chi(R) = <phi|R phi>/<phi|phi>). The characters are averaged per
     class and reduced into irreps with PointGroup.reduce_representation,
     which only ever uses the irreps that belong to that one target
     group (never irreps from another group). Because chi(E) = n is
     fixed by construction, the reduction is forced to sum to n, either
     as a single genuine irrep of dimension n, or as an accidental
     degeneracy of several smaller irreps, both cases are reported
     explicitly. The best-fitting orientation (integer-closest
     reduction) is reported.
  5. Groups that cannot occur in a cubic cell (e.g. C_5v, D_5, or the
     icosahedral/continuous groups) are still looked up in
     point_groups_lib.py exactly like any other group; the generic subgroup
     search then correctly reports that no realization exists inside
     O_h, rather than silently doing something wrong.

Defect location and point-group information:
  All of this is always read from a file named correction.json: in the working 
  directory by default, or in the PARENT of the working directory with --qe. 
  'defect_frac_coords' is used as the symmetry center, and the 'point group' block
  (perfect/defect, Hermann-Mauguin/Schoenflies) is printed for reference
  and used to pick the target group. --target lets you force the
  analysis for any point group in point_groups_lib.py's catalog directly
  (overrides the label read from correction.json).

Number of BANDS given = degeneracy order analyzed:
  1 band  -> non-degenerate case (n=1)
  2 bands -> doubly-degenerate case (n=2)
  3 bands -> triply-degenerate case (n=3)
  ... and so on for any n, as long as the target point group actually
  has a way to realize it (a genuine n-D irrep, or an accidental sum
  of smaller irreps), see describe_multiplet().

Real and imaginary parts (optional, per band):
  Each band may be given as a single real-valued file, or
  as a REAL + IMAGINARY pair to build a complex orbital phi = real +
  i*imag. Pairing is automatic, based on the same '..._r.EXT' /
  '..._i.EXT' naming already used for the real-only files (EXT =
  'vasp' by default, 'xsf' with --qe): two files sharing everything up
  to a trailing '_r'/'_i' before the extension (e.g.
  wfc_s2_k1_b430_r.vasp and wfc_s2_k1_b430_i.vasp, sharing base
  'wfc_s2_k1_b430') are combined into ONE complex band. A file given
  on its own -- only the '_r' one, only the '_i' one, or a filename
  that doesn't follow the '_r'/'_i' convention at all -- is treated as
  a single real-valued band, exactly as before, so old-style
  invocations are unaffected. Complex and real-valued bands can be
  freely mixed within one run (see read_multi/pair_real_imag_files).
  Overlaps <i|R j> then use the proper complex inner product (conjugate
  the bra); the resulting per-class characters are averaged and their
  real part taken (a non-negligible imaginary part triggers a warning,
  since the characters of these point groups are real).
"""

import argparse
import json
import os
import re
from itertools import permutations, product

import numpy as np
from scipy.ndimage import map_coordinates

import point_groups_lib

def read_vesta_grid(path):
    """Parses a VESTA/CHGCAR-like file: lattice + grid dims + volumetric data."""
    with open(path) as f:
        lines = f.readlines()

    scale = float(lines[1])
    lattice = np.array([[float(x) for x in lines[i].split()] for i in (2, 3, 4)]) * scale

    counts = [int(x) for x in lines[6].split()]
    natoms = sum(counts)

    coord_start = 8                      # 'Direct'/'Cartesian' line is lines[7]
    coord_end = coord_start + natoms

    grid_line_idx = coord_end + 1        # there's a blank line before the dims
    nx, ny, nz = (int(x) for x in lines[grid_line_idx].split())

    text = ''.join(lines[grid_line_idx + 1:])
    # np.fromstring(..., sep=' ') parses the numeric text directly in C,
    # instead of first building a Python list of millions of strings with
    # str.split() and then casting each one (np.array(text.split(), ...)) --
    # meaningfully faster for the multi-million-value grids these files
    # contain, with identical results.
    data_flat = np.fromstring(text, dtype=float, sep=' ')
    data_flat = data_flat[: nx * ny * nz]
    grid = data_flat.reshape((nx, ny, nz), order='F')   # x fastest (VASP convention)

    return lattice, grid, (nx, ny, nz)

def _read_primvec(lines):
    """Parses the 'PRIMVEC' block of an .xsf file (3 lattice-vector lines
    right after the keyword), if present. Not used by the group-theory
    engine itself (which only needs the grid shape), kept purely for
    reference/printing, mirroring read_vesta_grid's lattice return
    value. Returns None if no PRIMVEC block is found (some .xsf files
    only carry CONVVEC, or none at all)."""
    for idx, line in enumerate(lines):
        if line.strip() == "PRIMVEC":
            return np.array([[float(x) for x in lines[idx + 1 + i].split()]
                              for i in range(3)])
    return None

def read_xsf_grid(path):
    """Parses a Quantum ESPRESSO .xsf file (--qe mode): lattice vectors
    (PRIMVEC, for reference only) + the volumetric data embedded in its
    'BEGIN_BLOCK_DATAGRID_3D' / 'BEGIN_DATAGRID_3D_...' section (as
    written e.g. by pp.x, or by converting a band-resolved real-space
    QE dump to .xsf).

    XCrySDen's convention for periodic 3D data is to repeat the first
    grid point as an extra point at the end of each axis (so a genuine
    nx x ny x nz FFT grid, as QE itself uses it, is stored on disk as
    (nx+1) x (ny+1) x (nz+1) values); that redundant last layer along
    each axis is dropped here to recover the intrinsic FFT grid, so the
    rest of the script (which expects one value per FFT grid point,
    exactly as read_vesta_grid provides for VASP) sees the same kind of
    array either way."""
    with open(path) as f:
        lines = f.readlines()

    lattice = _read_primvec(lines)

    grid_start = None
    for idx, line in enumerate(lines):
        if line.strip().startswith("BEGIN_DATAGRID_3D"):
            grid_start = idx
            break
    if grid_start is None:
        raise RuntimeError(f"{path}: no BEGIN_DATAGRID_3D block found -- this "
                            f"script needs an .xsf file with an embedded "
                            f"volumetric datagrid (e.g. from pp.x), not a bare "
                            f"structure file.")

    nx1, ny1, nz1 = (int(x) for x in lines[grid_start + 1].split()[:3])
    data_start = grid_start + 6

    end = None
    for idx in range(data_start, len(lines)):
        if lines[idx].strip().startswith("END_DATAGRID_3D"):
            end = idx
            break
    if end is None:
        raise RuntimeError(f"{path}: BEGIN_DATAGRID_3D with no matching "
                            f"END_DATAGRID_3D")

    text = ''.join(lines[data_start:end])
    data_flat = np.fromstring(text, dtype=float, sep=' ')
    data_flat = data_flat[: nx1 * ny1 * nz1]
    full = data_flat.reshape((nx1, ny1, nz1), order='F')   # x fastest, like QE/VASP

    # Drop XCrySDen's redundant periodic-repeat point along each axis.
    grid = full[:-1, :-1, :-1]
    nx, ny, nz = grid.shape

    return lattice, grid, (nx, ny, nz)

def load_json(path):
    """Reads a correction.json and returns (defect_frac_coords, point_group_info)."""
    with open(path) as f:
        data = json.load(f)

    if "defect_frac_coords" not in data:
        raise KeyError(f"{path}: key 'defect_frac_coords' not found")
    defect_frac_coords = tuple(float(x) for x in data["defect_frac_coords"])

    point_group = data.get("point group", data.get("point_group", {}))

    return defect_frac_coords, point_group

def print_point_group(point_group):
    """Pretty-prints the perfect/defect point-group block from correction.json."""
    print("Point group (from correction.json):")
    for label in ("perfect", "defect"):
        info = point_group.get(label, {})
        hm = info.get("Hermann-Mauguin", "?")
        sf = info.get("Schoenflies", "?")
        print(f"  {label:8s}: Hermann-Mauguin = {hm!r:8s}  Schoenflies = {sf!r}")

def resolve_target_group(point_group):
    """Normalizes the defect's Schoenflies label (correction.json) to the
    naming used by point_groups_lib.py, e.g. 'C3v' -> 'C_3v'. Returns None if
    no usable label is available."""
    if not point_group:
        return None
    label = point_group.get("defect", {}).get("Schoenflies")
    if not label:
        return None
    try:
        return point_groups_lib.create_point_group(label).name
    except KeyError:
        return None

def resolve_center_and_point_group(qe=False):
    """Resolves the symmetry center and point-group info from
    correction.json and returns (center, point_group_or_None).

    In --qe mode the file is looked up one directory up ('../correction.json'),
    matching the layout the original QE-branch script expected; the default
    (VASP) mode looks it up in the working directory, as before."""
    path = "../correction.json" if qe else "correction.json"
    defect_frac_coords, point_group = load_json(path)
    return defect_frac_coords, point_group

# Apply a symmetry operation to the grid (periodic interpolation)
def base_offsets(shape, center_frac):
    """Precomputes the (i/nx-cx, j/ny-cy, k/nz-cz) fractional offsets ONCE
    for a given grid shape and symmetry center. These depend only on the
    (fixed, per-run) grid and defect center -- NOT on the operation R -- so
    recomputing them from scratch inside apply_operation on every single
    call (as before) was pure waste: for a 164^3 grid this np.indices +
    stack step alone was repeated for every operation, of every class, of
    every candidate orientation, of every point group tried."""
    nx, ny, nz = shape
    i, j, k = np.indices(shape)
    return np.stack([i / nx - center_frac[0],
                      j / ny - center_frac[1],
                      k / nz - center_frac[2]], axis=-1)

def apply_operation(grid, shape, center_frac, R, s=None):
    """Returns the grid transformed by operation R about center_frac
    (fractional coordinates), via periodic interpolation. Works for both
    real-valued and complex-valued grids: map_coordinates only accepts
    real input, so a complex grid is interpolated as its real and
    imaginary parts separately and recombined, geometrically this is
    exactly the same rotation/interpolation applied to both parts.

    's' is the precomputed base_offsets(shape, center_frac); pass it in
    (as class_traces now does) to avoid rebuilding it on every call. If
    omitted it is computed on the fly, so any external/older caller of
    this function keeps working exactly as before."""
    nx, ny, nz = shape
    if s is None:
        s = base_offsets(shape, center_frac)

    s_rot = s @ R   # equivalent to R^-1 @ s since R is orthogonal (R^-1 = R^T)

    new_frac = s_rot + np.array(center_frac)
    new_idx = new_frac * np.array([nx, ny, nz])

    coords = [new_idx[..., 0], new_idx[..., 1], new_idx[..., 2]]
    if np.iscomplexobj(grid):
        real_part = map_coordinates(grid.real, coords, order=3, mode='wrap')
        imag_part = map_coordinates(grid.imag, coords, order=3, mode='wrap')
        return real_part + 1j * imag_part
    return map_coordinates(grid, coords, order=3, mode='wrap')

_RI_SUFFIX_RE = re.compile(r'^(.*)_([ri])(\.[^.]+)$')

def pair_real_imag_files(paths):
    """Groups the given .vasp paths into one entry per BAND, auto-pairing
    real/imaginary parts using the same '..._r.vasp' / '..._i.vasp'
    naming already in use: two files whose basenames share everything up
    to a trailing '_r' or '_i' before the extension (e.g.
    'wfc_s2_k1_b430_r.vasp' and 'wfc_s2_k1_b430_i.vasp' both have base
    'wfc_s2_k1_b430') are grouped into the same band. A file given
    without its '_r'/'_i' partner -- or whose name doesn't follow that
    convention at all -- becomes its own band with only one part set (so
    plain real-only usage, including filenames with no suffix, is
    unaffected).

    Returns a list of {'real': path_or_None, 'imag': path_or_None,
    'label': str}, one per band, in the order each band first appears on
    the command line."""
    groups, order = {}, []
    for p in paths:
        d, fname = os.path.split(p)
        m = _RI_SUFFIX_RE.match(fname)
        if m:
            base, kind, ext = m.groups()
            key = (d, base, ext)
            label = os.path.join(d, base + ext) if d else base + ext
        else:
            key, kind, label = ('__solo__', p), None, p

        if key not in groups:
            groups[key] = {'real': None, 'imag': None, 'label': label}
            order.append(key)
        if kind == 'r':
            groups[key]['real'] = p
        elif kind == 'i':
            groups[key]['imag'] = p
        else:
            groups[key]['real'] = p

    return [groups[k] for k in order]

def read_multi(paths, reader=read_vesta_grid):
    """Reads the given files into one grid per band (real ndarray, or
    complex ndarray = real + 1j*imag for a paired band; see
    pair_real_imag_files). All bands must share the same FFT grid
    shape.

    'reader' is the per-file grid reader to use: read_vesta_grid (.vasp,
    the default) or read_xsf_grid (.xsf, --qe mode)."""
    bands = pair_real_imag_files(paths)
    grids, shape_ref = [], None
    for b in bands:
        if b['real'] and b['imag']:
            _, g_re, shp_re = reader(b['real'])
            _, g_im, shp_im = reader(b['imag'])
            if shp_re != shp_im:
                raise RuntimeError(f"{b['real']} and {b['imag']}: grid shapes "
                                    f"do not match ({shp_re} vs {shp_im})")
            grid, shp, kind = g_re + 1j * g_im, shp_re, "complex (real+imag)"
        elif b['real']:
            _, grid, shp = reader(b['real'])
            kind = "real"
        else:
            # Only the '_i' file was given for this band, with no '_r'
            # partner: a genuine purely-imaginary band (0 + i*imag),
            # not a reinterpretation of those numbers as a real grid.
            _, g_im, shp = reader(b['imag'])
            grid, kind = 1j * g_im, "purely imaginary"

        if shape_ref is None:
            shape_ref = shp
        elif shp != shape_ref:
            raise RuntimeError(f"{b['label']}: grid {shp} does not match {shape_ref}")

        print(f"   band {len(grids) + 1}: {b['label']}  [{kind}]")
        grids.append(grid)
    return grids, shape_ref

def class_traces(grids, shape, center, ops, s=None, transform_cache=None):
    """Trace of the (normalized) overlap matrix S_ij(R) = <i|R|j> for each
    operation R in ops. Generic for any n = len(grids): for n=1 this is
    exactly the familiar chi(R) = <phi|R phi>/<phi|phi>. Also generic for
    real- or complex-valued bands (any mix): the proper complex inner
    product <i|Rj> = sum(conj(phi_i) * R(phi_j)) is used throughout,
    which reduces to the plain real dot product when all bands are
    real-valued (conj is a no-op there), so real-only usage is
    numerically unchanged. The orthogonality of the input bands is
    checked once by the caller (analyze_multiplet), not on every call
    here, to avoid repeating the same warning once per class per
    orientation.

    's' is the precomputed base_offsets(shape, center) (see
    apply_operation). 'transform_cache', if given, is a dict shared across
    the whole run keyed by (band_index, operation_matrix): the SAME
    physical rotation/reflection R very often occurs in more than one
    orientation of a group, and -- when no --target is given and the
    script falls back to trying T_d, D_2d, C_3v, C_2v, S_4 in turn -- in
    more than one of those groups too, since they are all realized as
    different subgroups of the same 48 O_h operations. Without the cache
    each occurrence re-runs the (expensive) periodic cubic-spline
    interpolation from scratch on the full grid; with it, each distinct R
    is interpolated at most once per band for the entire run."""
    if s is None:
        s = base_offsets(shape, center)
    if transform_cache is None:
        transform_cache = {}

    n = len(grids)
    norms = [np.sum(np.abs(g) ** 2) for g in grids]
    traces = []
    for R in ops:
        r_key = _mat_key(R)
        transformed = []
        for gi, g in enumerate(grids):
            cache_key = (gi, r_key)
            if cache_key not in transform_cache:
                transform_cache[cache_key] = apply_operation(g, shape, center, R, s=s)
            transformed.append(transform_cache[cache_key])
        S = np.zeros((n, n), dtype=complex)
        for i in range(n):
            for j in range(n):
                S[i, j] = np.sum(np.conj(grids[i]) * transformed[j]) / np.sqrt(norms[i] * norms[j])
        traces.append(np.trace(S))
    return traces

def real_character(trace_values, class_label, tol=1e-3):
    """Averages the per-operation trace_values of one class into a single
    character. class_traces returns complex numbers in general (to
    support complex-valued bands); the character tables in
    point_groups_lib.py are real, so the real part is taken and a warning is
    printed if a non-negligible imaginary part remains -- which would
    signal either a genuinely complex irrep (not represented in this
    catalog) or real/imaginary parts that don't actually belong to a
    consistent wavefunction (e.g. mismatched or swapped _r/_i files)."""
    mean = np.mean(np.asarray(trace_values, dtype=complex))
    if abs(mean.imag) > tol:
        print(f"   WARNING: class '{class_label}' has a non-negligible "
              f"imaginary character ({mean.imag:+.4f}); using its real "
              f"part ({mean.real:+.4f}). Check that paired _r/_i files "
              f"correspond to the same band.")
    return float(mean.real)

# Generic utilities that use point_groups_lib.py to reduce
def decomposition_quality(decomposition):
    """How far the reduction coefficients are from integers; 0 = perfect
    decomposition (a better indicator of the correct axis/group than an
    ad-hoc Euclidean distance)."""
    return sum((v - round(v)) ** 2 for v in decomposition.values())

def summarize_decomposition(decomposition):
    contributing = {irrep: n for irrep, n in decomposition.items() if n}
    if not contributing:
        return "0 (no irrep)"
    return " + ".join(f"{n} x {irrep}" if n != 1 else irrep
                       for irrep, n in contributing.items())

def print_decomposition(pg, decomposition, title):
    print(f"\n{title}")
    for irrep in pg.irreps:
        print(f"   {irrep:6s}: {decomposition.get(irrep, 0)}")
    print(f"   => {summarize_decomposition(decomposition)}")

def describe_multiplet(decomposition, n):
    """Physically interprets a decomposition of n bands (n = number of
    input .vasp files = degeneracy order being sought): generic for any
    n, with no special cases per value of n. Since chi(E) = n is fixed
    by construction, the reduction into irreps ALWAYS sums to n; the
    only thing that can vary is whether that is achieved with a single
    irrep (a genuine multiplet of dimension n, forced by symmetry) or
    with several smaller irreps summed together (accidental
    degeneracy, i.e. without symmetry protection)."""
    contributing = [(irrep, mult) for irrep, mult in decomposition.items()
                    if round(mult) != 0]
    if len(contributing) == 1 and round(contributing[0][1]) == 1:
        irrep, _ = contributing[0]
        return (f"Genuine multiplet: the {n} input band(s) form a single "
                f"degenerate irrep '{irrep}' of dimension {n}, protected "
                f"by the symmetry of the group.")
    if len(contributing) == 1:
        irrep, mult = contributing[0]
        return (f"The {n} input band(s) reduce to {mult} copy(ies) of the "
                f"irrep '{irrep}' (multiplicity {mult} of an irrep whose "
                f"dimension, multiplied by {mult}, gives the total {n}).")
    parts = ", ".join(f"{mult} x {irrep}" for irrep, mult in contributing)
    return (f"ACCIDENTAL degeneracy: the {n} input band(s) do not form a "
            f"single irrep of dimension {n}, but the sum of several "
            f"distinct irreps ({parts}) -- i.e. it is not protected by "
            f"the symmetry of this group in this orientation.")

# Generic subgroup engine: builds the parent group O_h (48 ops) and
# finds ANY subgroup from point_groups_lib.py's catalog inside it, using
# real group theory (closure + conjugacy classes) instead of
# hand-written geometric logic per group.

def build_parent_operations():
    """The 48 operations of O_h (full cubic holohedry): every subgroup
    that point_groups_lib.py can identify in a cubic cell (VASP,
    zincblende/rocksalt/diamond-type) is a subgroup of this one, so it
    replaces the 24 operations of T_d previously used as the universal
    parent frame (T_d is itself one of the subgroups this engine finds
    inside O_h)."""
    def perm_matrix(p):
        M = np.zeros((3, 3))
        for i, j in enumerate(p):
            M[j, i] = 1
        return M

    perms = [perm_matrix(p) for p in permutations(range(3))]
    signs = [np.diag(d) for d in product((1, -1), repeat=3)]
    ops = [P @ D for P in perms for D in signs]
    assert len(ops) == 48
    return ops

def _mat_key(M, decimals=6):
    return tuple(np.round(M, decimals).flatten())

def group_closure(generators, max_size=48):
    """Closes a set of matrices under multiplication (includes I). Cuts
    off at max_size to avoid over-generating when the generators
    produce all of O_h.

    Kept for backward compatibility (e.g. external callers/notebooks that
    import it directly). all_subgroups() itself no longer uses this --
    see build_multiplication_table/_closure_idx below for the fast path."""
    elements = {_mat_key(np.eye(3)): np.eye(3)}
    for g in generators:
        elements[_mat_key(g)] = g
    frontier = list(elements.values())
    while frontier:
        new_frontier = []
        current = list(elements.values())
        for a in frontier:
            for b in current:
                for M in (a @ b, b @ a):
                    k = _mat_key(M)
                    if k not in elements:
                        elements[k] = M
                        new_frontier.append(M)
        frontier = new_frontier
        if len(elements) > max_size:
            break
    return list(elements.values())

def build_multiplication_table(parent_ops):
    """Precomputes the Cayley (multiplication) table of parent_ops ONCE:
    mult[a][b] = index (into parent_ops) of parent_ops[a] @ parent_ops[b].

    all_subgroups() needs to close many different generator sets under
    multiplication, and group_closure (above) used to do that by literally
    recomputing 3x3 numpy matrix products -- with rounding + tuple-key
    hashing -- for the same handful of products over and over (thousands
    of times for O_h's 48 elements). Since parent_ops never changes within
    a run, every product it could ever need is computed here exactly once
    (48x48 = 2304 tiny matmuls), and every closure afterwards is pure
    integer set/lookup work via _closure_idx. This alone turns
    all_subgroups() from roughly a minute into a few milliseconds."""
    n = len(parent_ops)
    key_to_idx = {_mat_key(m): i for i, m in enumerate(parent_ops)}
    mult = [[0] * n for _ in range(n)]
    for a in range(n):
        for b in range(n):
            mult[a][b] = key_to_idx[_mat_key(parent_ops[a] @ parent_ops[b])]
    id_idx = key_to_idx[_mat_key(np.eye(3))]
    return mult, id_idx

def _closure_idx(gen_idx, mult, id_idx, max_size):
    """Same fixed-point closure as group_closure, but operating on
    operation INDICES via the precomputed multiplication table instead of
    on 3x3 matrices via numpy -- see build_multiplication_table."""
    elements = {id_idx}
    elements.update(gen_idx)
    frontier = list(elements)
    while frontier:
        current = list(elements)
        new_frontier = []
        for a in frontier:
            row_a = mult[a]
            for b in current:
                for c in (row_a[b], mult[b][a]):
                    if c not in elements:
                        elements.add(c)
                        new_frontier.append(c)
        frontier = new_frontier
        if len(elements) > max_size:
            break
    return elements

def conjugacy_classes(H):
    """Partitions H (a list of matrices forming a closed group) into its
    REAL conjugacy classes, computed by matrix multiplication (x g x^-1,
    with x^-1 = x^T since they are orthogonal) -- with no group-specific
    geometric knowledge."""
    keys = {_mat_key(g): g for g in H}
    remaining = set(keys.keys())
    classes = []
    while remaining:
        g_key = next(iter(remaining))
        g = keys[g_key]
        orbit = set()
        for x in H:
            conj = x @ g @ x.T
            orbit.add(_mat_key(conj))
        orbit &= set(keys.keys())
        classes.append([keys[k] for k in orbit])
        remaining -= orbit
    return classes


def all_subgroups(parent_ops, max_rounds=6):
    """Enumerates ALL subgroups of parent_ops (a finite group of
    matrices, closed under multiplication). It is not enough to close
    pairs of elements as generators -- some subgroups (e.g. D_2h, which
    as an abstract group is Z2 x Z2 x Z2) need 3 generators. Instead of
    guessing how many generators each group needs, it starts from the
    cyclic subgroups (generated by a single element) and iteratively
    closes all pairwise unions of subgroups already found until reaching
    a fixed point -- this way any subgroup is found with no prior
    knowledge of its structure. Returns {key: [matrices]} (one entry per
    distinct subgroup found; the key just needs to be unique/hashable --
    see build_multiplication_table -- nothing downstream reads its
    content, only subgroup_catalog.values()).

    Performance note: this used to close every generator set by
    repeated numpy matrix multiplication (group_closure), which took
    close to a minute for O_h because it kept recomputing the same
    products. It now precomputes the 48x48 Cayley table once
    (build_multiplication_table) and does every closure as integer table
    lookups (_closure_idx); the result is mathematically identical, just
    computed in milliseconds instead of tens of seconds."""
    n = len(parent_ops)
    mult, id_idx = build_multiplication_table(parent_ops)

    found = {}   # frozenset(indices) -> set(indices)
    for g in range(n):
        H = _closure_idx([g], mult, id_idx, max_size=n)
        found.setdefault(frozenset(H), H)

    for _ in range(max_rounds):
        keys = list(found.keys())
        added = False
        for a in range(len(keys)):
            for b in range(a, len(keys)):
                gens = list(found[keys[a]]) + list(found[keys[b]])
                H = _closure_idx(gens, mult, id_idx, max_size=n)
                key = frozenset(H)
                if key not in found:
                    found[key] = H
                    added = True
        if not added:
            break

    # The rest of the script (conjugacy_classes, apply_operation, ...)
    # works with actual matrices, so convert the index sets back here,
    # at the very end -- once, not per-closure.
    return {key: [parent_ops[i] for i in idx_set] for key, idx_set in found.items()}

def find_candidate_subgroups(subgroup_catalog, target_order):
    """Filters the subgroup catalog (from all_subgroups) by order."""
    return [H for H in subgroup_catalog.values() if len(H) == target_order]

def label_signature(label):
    """Interprets a standard class label ('E', 'i', 'sigma...', 'C{m}',
    'C{m}^{k}', 'S{m}', 'S{m}^{k}', with or without primes) as
    (is_proper, expected_trace). Returns None if the pattern is not
    recognized (this only weakens the signature tie-break; matching by
    class size still works)."""
    import re
    if label == "E":
        return (True, 3.0)
    if label == "i":
        return (False, -3.0)
    if label.startswith("sigma"):
        return (False, 1.0)
    m = re.match(r"^([CS])(\d+)(?:\^(\d+))?", label)
    if m:
        letter, order_s, k_s = m.groups()
        order = int(order_s)
        k = int(k_s) if k_s else 1
        angle = 2 * np.pi * k / order
        if letter == "C":
            return (True, round(1 + 2 * np.cos(angle), 3))
        return (False, round(-1 + 2 * np.cos(angle), 3))
    return None

def match_classes_to_labels(computed_classes, pg):
    """Matches the computed (unlabeled) conjugacy classes to the labels
    declared in pg.classes, using class size + signature
    (proper/improper, trace) inferred from the label text. When two or
    more labels share the exact same signature (e.g. C2' vs C2'' in
    D_4, or sigma_v vs sigma_d) their physical identity is not
    determined by the matrices alone; they are assigned in a fixed,
    reproducible order (documented in the module's README) so the
    computation is deterministic.

    Returns {label: [matrices]} or None if computed_classes is not a
    valid realization of pg (incompatible class sizes)."""
    got_sizes = sorted(len(c) for c in computed_classes)
    want_sizes = sorted(mult for _, mult in pg.classes)
    if got_sizes != want_sizes:
        return None

    id_key = _mat_key(np.eye(3))
    identity_class = None
    others = []
    for c in computed_classes:
        if any(_mat_key(m) == id_key for m in c):
            identity_class = c
        else:
            others.append(c)
    if identity_class is None:
        return None

    def csig(c):
        M = c[0]
        return (round(float(np.linalg.det(M))) == 1, round(float(np.trace(M)), 3))

    e_label = pg.classes[0][0]
    assignment = {e_label: identity_class}
    # index-based bookkeeping: numpy arrays inside `others` make list.remove()
    # / `in` ambiguous (elementwise comparison), so track "used" by index.
    remaining_idx = list(range(len(others)))
    unresolved = []

    def sig_of(i):
        return csig(others[i])

    for lbl, mult in pg.classes[1:]:
        parsed = label_signature(lbl)
        matches = [i for i in remaining_idx
                   if len(others[i]) == mult and (parsed is None or sig_of(i) == parsed)]
        if len(matches) == 1:
            assignment[lbl] = others[matches[0]]
            remaining_idx.remove(matches[0])
        else:
            unresolved.append((lbl, mult, parsed))

    groups = {}
    for lbl, mult, parsed in unresolved:
        groups.setdefault((mult, parsed), []).append(lbl)
    for (mult, parsed), labels in groups.items():
        cand_idx = [i for i in remaining_idx if len(others[i]) == mult
                    and (parsed is None or sig_of(i) == parsed)]
        if len(cand_idx) != len(labels):
            return None
        cand_idx_sorted = sorted(cand_idx,
                                  key=lambda i: tuple(sorted(_mat_key(others[i][0]))))
        for lbl, i in zip(labels, cand_idx_sorted):
            assignment[lbl] = others[i]
            remaining_idx.remove(i)

    if remaining_idx:
        return None
    return assignment

def find_group_embeddings(subgroup_catalog, pg, max_embeddings=8):
    """Finds up to max_embeddings concrete realizations of pg inside
    subgroup_catalog (the COMPLETE catalog of O_h subgroups produced by
    all_subgroups -- not just those generated by pairs, but also those
    needing 3+ generators, like D_2h), each one {label: [matrices]}.
    Different realizations correspond to different physical
    orientations (e.g. the four <111> axes for C_3v) -- what used to be
    done by hand via c3v_operations_by_axis/d2d_operations_by_axis, now
    automatic for any group in the catalog."""
    if pg.order is None:
        raise ValueError(f"'{pg.name}' is a continuous group; it has no "
                          f"finite matrix representation here.")
    candidates = find_candidate_subgroups(subgroup_catalog, pg.order)
    embeddings, seen = [], set()
    for H in candidates:
        assignment = match_classes_to_labels(conjugacy_classes(H), pg)
        if assignment is None:
            continue
        key = frozenset(_mat_key(m) for ms in assignment.values() for m in ms)
        if key in seen:
            continue
        seen.add(key)
        embeddings.append(assignment)
        if len(embeddings) >= max_embeddings:
            break
    return embeddings

# Generic analysis by point group AND by degeneracy order n (replaces
# analyze_td/analyze_c3v/analyze_d2d -- hand-written just for those 3
# groups -- and also the old split analyze_point_group (1 band) /
# analyze_point_group_multiband (2+ bands): both fundamentally used the
# same character formula -- the trace of the n x n overlap matrix --
# so they are unified into a single function that serves n=1,2,3,...
# with no special case.)

def analyze_multiplet(grids, shape, center, pg, subgroup_catalog, s=None, transform_cache=None):
    """Finds every realization of pg inside subgroup_catalog (the
    complete catalog of O_h subgroups produced by all_subgroups),
    measures chi(R) = Tr[S(R)] per class in each one (S is the
    normalized overlap matrix of the n given bands -- n = len(grids) is
    the degeneracy order being analyzed: 1 band = non-degenerate case,
    2 bands = doubly degenerate, 3 = triply degenerate, and so on for
    any n), reduces using ONLY the irreps that belong to pg
    (PointGroup.reduce_representation), and reports the best-fitting
    orientation along with whether the multiplet is a genuine irrep of
    dimension n or an accidental degeneracy.

    's' (precomputed base_offsets) and 'transform_cache' (shared
    per-operation interpolation cache) are threaded through from main()
    so that repeated work is avoided both within this call and across
    successive calls (e.g. the T_d/D_2d/C_3v/C_2v/S_4 fallback when no
    --target/correction.json group is known). If omitted, fresh ones are
    created (this call still works standalone, just without cross-call
    reuse)."""
    if s is None:
        s = base_offsets(shape, center)
    if transform_cache is None:
        transform_cache = {}
    embeddings = find_group_embeddings(subgroup_catalog, pg)
    if not embeddings:
        print(f"\n   No realization of '{pg.name}' was found within the "
              f"O_h subgroup catalog. If '{pg.name}' is not compatible "
              f"with a cubic cell (e.g. order-5 symmetries, or "
              f"icosahedral/continuous groups), this is expected.")
        return None, None

    n = len(grids)
    if n > 1:
        norms = [np.sum(np.abs(g) ** 2) for g in grids]
        ortho = np.array([[np.sum(np.conj(grids[i]) * grids[j]) / np.sqrt(norms[i] * norms[j])
                            for j in range(n)] for i in range(n)])
        off_diag = ortho - np.diag(np.diag(ortho))
        if np.max(np.abs(off_diag)) > 0.05:
            print(f"   WARNING: bands are not perfectly orthogonal to each other "
                  f"(max |<i|j>| off diagonal = {np.max(np.abs(off_diag)):.3f})")

    e_label = pg.class_labels[0]
    print(f"\n--- Multiplet analysis (n={n} band(s), degeneracy order "
          f"sought = {n}) under {pg.name} "
          f"({len(embeddings)} candidate orientation(s)) ---")
    best = None
    for idx, ops_by_class in enumerate(embeddings, start=1):
        measured = []
        for c in pg.class_labels:
            if c == e_label:
                measured.append(float(n))
            else:
                measured.append(real_character(class_traces(grids, shape, center,
                                                              ops_by_class[c], s=s,
                                                              transform_cache=transform_cache), c))
        decomposition = pg.reduce_representation(measured)
        quality = decomposition_quality(decomposition)
        vals = ", ".join(f"{v:6.3f}" for v in measured)
        print(f"   Orientation {idx}: ({', '.join(pg.class_labels)}) = [{vals}]  "
              f"-> {summarize_decomposition(decomposition)}  (residual={quality:.4f})")
        if best is None or quality < best[0]:
            best = (quality, idx, measured, decomposition)

    _, idx, measured, decomposition = best
    print(f"\n=> Best orientation: #{idx}")
    print_decomposition(pg, decomposition, f"Decomposition into irreps of {pg.name}:")
    print(f"   {describe_multiplet(decomposition, n)}")
    return measured, decomposition

def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("files", nargs="+",
                     help="One or more input files: .vasp by default, or "
                          ".xsf if --qe is given. Each BAND is either one "
                          "real-valued file, or a real+imaginary pair "
                          "auto-combined into one complex band by the "
                          "'..._r.EXT'/'..._i.EXT' naming convention (e.g. "
                          "wfc_s2_k1_b430_r.vasp wfc_s2_k1_b430_i.vasp -> 1 "
                          "complex band); give only the '_r' file (or a name "
                          "without that suffix) for a plain real band, as "
                          "before. n BANDS (real, complex, or a mix) analyze "
                          "the n-fold degenerate case: 1 band = "
                          "non-degenerate, 2 = doubly degenerate, 3 = "
                          "triply degenerate, and so on for any n.")
    ap.add_argument("--qe", action="store_true",
                     help="Read Quantum ESPRESSO .xsf files (XCrySDen format, "
                          "e.g. from pp.x) instead of the default VASP/VESTA "
                          ".vasp format. Also switches the correction.json "
                          "lookup to '../correction.json', matching the "
                          "original QE-branch script's layout.")
    ap.add_argument("--target", type=str, default=None,
                     help="Force the analysis for a specific point group (any name "
                          "point_groups_lib.py recognizes, e.g. 'C_3v', 'D_2d', 'D_5'), "
                          "overriding the Schoenflies label read from correction.json.")
    args = ap.parse_args()

    reader = read_xsf_grid if args.qe else read_vesta_grid

    center, point_group_info = resolve_center_and_point_group(qe=args.qe)
    parent_ops = build_parent_operations()
    subgroup_catalog = all_subgroups(parent_ops)
    print(f"O_h subgroup catalog: {len(subgroup_catalog)} distinct subgroups "
          f"(from the {len(parent_ops)} elements of O_h).\n")

    if point_group_info:
        print_point_group(point_group_info)
        print()

    if args.target:
        target_key = point_groups_lib.create_point_group(args.target).name
    else:
        target_key = resolve_target_group(point_group_info)

    print(f"Reading input bands ({'QE .xsf' if args.qe else 'VASP .vasp'} "
          f"format; real/imaginary pairs auto-detected by '_r'/'_i' "
          f"filename suffix):")
    grids, shape = read_multi(args.files, reader=reader)
    n = len(grids)

    print(f"\nGrid: {shape[0]} x {shape[1]} x {shape[2]}")
    print(f"Symmetry center (fractional): {center}")
    print(f"Input bands: {n}   =>   degeneracy order sought: n = {n}")

    # Precomputed once, shared across every analyze_multiplet call below:
    # 's' is the grid's fixed fractional-offset field (independent of which
    # operation/group is being tested), and 'transform_cache' remembers,
    # per band, every rotated/reflected grid already interpolated -- so
    # when the SAME physical operation shows up again (a different
    # orientation of the same group, or a different candidate group
    # entirely in the no-target fallback below), it is reused instead of
    # recomputed.
    s = base_offsets(shape, center)
    transform_cache = {}

    if target_key:
        # The defect's point group is already known (via --target or
        # correction.json): analyze ONLY that group, with its own
        # irreps -- never T_d or any other reference group.
        pg = point_groups_lib.create_point_group(target_key)
        analyze_multiplet(grids, shape, center, pg, subgroup_catalog, s=s,
                           transform_cache=transform_cache)
    else:
        # No known point group: use T_d as the initial reference (the
        # most common ideal-defect case), and if it doesn't fit well,
        # try the most common subgroups for point defects in cubic
        # cells.
        td = point_groups_lib.create_point_group("T_d")
        _, decomposition_td = analyze_multiplet(grids, shape, center, td, subgroup_catalog,
                                                  s=s, transform_cache=transform_cache)
        quality_td = decomposition_quality(decomposition_td) if decomposition_td else None

        if quality_td is None or quality_td > 0.05:
            print("\n   NOTICE: the ideal T_d symmetry does not fit well (or "
                  "could not be reduced) and no usable defect point group "
                  "was given; trying common point-defect subgroups in cubic "
                  "cells (D_2d, C_3v, C_2v, S_4).")
            for name in ("D_2d", "C_3v", "C_2v", "S_4"):
                pg = point_groups_lib.create_point_group(name)
                analyze_multiplet(grids, shape, center, pg, subgroup_catalog,
                                   s=s, transform_cache=transform_cache)

if __name__ == "__main__":
    main()
